// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: de/fhwedel/ueb04/LogMessage.proto

package de.fhwedel.ueb04;

public final class LogMessageProtos {
  private LogMessageProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:messages.LogMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string timestamp = 1;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required string timestamp = 1;</code>
     */
    java.lang.String getTimestamp();
    /**
     * <code>required string timestamp = 1;</code>
     */
    com.google.protobuf.ByteString
        getTimestampBytes();

    /**
     * <code>optional .messages.LogMessage.ID id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>optional .messages.LogMessage.ID id = 2;</code>
     */
    de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID getId();
    /**
     * <code>optional .messages.LogMessage.ID id = 2;</code>
     */
    de.fhwedel.ueb04.LogMessageProtos.LogMessage.IDOrBuilder getIdOrBuilder();

    /**
     * <code>required .messages.LogMessage.Priority priority = 3;</code>
     */
    boolean hasPriority();
    /**
     * <code>required .messages.LogMessage.Priority priority = 3;</code>
     */
    de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority getPriority();

    /**
     * <code>required string content = 4;</code>
     */
    boolean hasContent();
    /**
     * <code>required string content = 4;</code>
     */
    java.lang.String getContent();
    /**
     * <code>required string content = 4;</code>
     */
    com.google.protobuf.ByteString
        getContentBytes();
  }
  /**
   * Protobuf type {@code messages.LogMessage}
   */
  public static final class LogMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:messages.LogMessage)
      LogMessageOrBuilder {
    // Use LogMessage.newBuilder() to construct.
    private LogMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogMessage(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogMessage defaultInstance;
    public static LogMessage getDefaultInstance() {
      return defaultInstance;
    }

    public LogMessage getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              timestamp_ = bs;
              break;
            }
            case 18: {
              de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = id_.toBuilder();
              }
              id_ = input.readMessage(de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(id_);
                id_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority value = de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                priority_ = value;
              }
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              content_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return de.fhwedel.ueb04.LogMessageProtos.internal_static_messages_LogMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return de.fhwedel.ueb04.LogMessageProtos.internal_static_messages_LogMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              de.fhwedel.ueb04.LogMessageProtos.LogMessage.class, de.fhwedel.ueb04.LogMessageProtos.LogMessage.Builder.class);
    }

    public static com.google.protobuf.Parser<LogMessage> PARSER =
        new com.google.protobuf.AbstractParser<LogMessage>() {
      public LogMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogMessage(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogMessage> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code messages.LogMessage.Priority}
     */
    public enum Priority
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>DEBUG = 0;</code>
       */
      DEBUG(0, 0),
      /**
       * <code>INFO = 1;</code>
       */
      INFO(1, 1),
      /**
       * <code>WARN = 2;</code>
       */
      WARN(2, 2),
      /**
       * <code>ERROR = 3;</code>
       */
      ERROR(3, 3),
      /**
       * <code>FATAL = 4;</code>
       */
      FATAL(4, 4),
      ;

      /**
       * <code>DEBUG = 0;</code>
       */
      public static final int DEBUG_VALUE = 0;
      /**
       * <code>INFO = 1;</code>
       */
      public static final int INFO_VALUE = 1;
      /**
       * <code>WARN = 2;</code>
       */
      public static final int WARN_VALUE = 2;
      /**
       * <code>ERROR = 3;</code>
       */
      public static final int ERROR_VALUE = 3;
      /**
       * <code>FATAL = 4;</code>
       */
      public static final int FATAL_VALUE = 4;


      public final int getNumber() { return value; }

      public static Priority valueOf(int value) {
        switch (value) {
          case 0: return DEBUG;
          case 1: return INFO;
          case 2: return WARN;
          case 3: return ERROR;
          case 4: return FATAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Priority>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Priority>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Priority>() {
              public Priority findValueByNumber(int number) {
                return Priority.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return de.fhwedel.ueb04.LogMessageProtos.LogMessage.getDescriptor().getEnumTypes().get(0);
      }

      private static final Priority[] VALUES = values();

      public static Priority valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private Priority(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:messages.LogMessage.Priority)
    }

    public interface IDOrBuilder extends
        // @@protoc_insertion_point(interface_extends:messages.LogMessage.ID)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>required string autor = 1;</code>
       */
      boolean hasAutor();
      /**
       * <code>required string autor = 1;</code>
       */
      java.lang.String getAutor();
      /**
       * <code>required string autor = 1;</code>
       */
      com.google.protobuf.ByteString
          getAutorBytes();

      /**
       * <code>required string location = 2;</code>
       */
      boolean hasLocation();
      /**
       * <code>required string location = 2;</code>
       */
      java.lang.String getLocation();
      /**
       * <code>required string location = 2;</code>
       */
      com.google.protobuf.ByteString
          getLocationBytes();
    }
    /**
     * Protobuf type {@code messages.LogMessage.ID}
     */
    public static final class ID extends
        com.google.protobuf.GeneratedMessage implements
        // @@protoc_insertion_point(message_implements:messages.LogMessage.ID)
        IDOrBuilder {
      // Use ID.newBuilder() to construct.
      private ID(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private ID(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final ID defaultInstance;
      public static ID getDefaultInstance() {
        return defaultInstance;
      }

      public ID getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private ID(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000001;
                autor_ = bs;
                break;
              }
              case 18: {
                com.google.protobuf.ByteString bs = input.readBytes();
                bitField0_ |= 0x00000002;
                location_ = bs;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.fhwedel.ueb04.LogMessageProtos.internal_static_messages_LogMessage_ID_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.fhwedel.ueb04.LogMessageProtos.internal_static_messages_LogMessage_ID_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.class, de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.Builder.class);
      }

      public static com.google.protobuf.Parser<ID> PARSER =
          new com.google.protobuf.AbstractParser<ID>() {
        public ID parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new ID(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<ID> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      public static final int AUTOR_FIELD_NUMBER = 1;
      private java.lang.Object autor_;
      /**
       * <code>required string autor = 1;</code>
       */
      public boolean hasAutor() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string autor = 1;</code>
       */
      public java.lang.String getAutor() {
        java.lang.Object ref = autor_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            autor_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string autor = 1;</code>
       */
      public com.google.protobuf.ByteString
          getAutorBytes() {
        java.lang.Object ref = autor_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          autor_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int LOCATION_FIELD_NUMBER = 2;
      private java.lang.Object location_;
      /**
       * <code>required string location = 2;</code>
       */
      public boolean hasLocation() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string location = 2;</code>
       */
      public java.lang.String getLocation() {
        java.lang.Object ref = location_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            location_ = s;
          }
          return s;
        }
      }
      /**
       * <code>required string location = 2;</code>
       */
      public com.google.protobuf.ByteString
          getLocationBytes() {
        java.lang.Object ref = location_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          location_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private void initFields() {
        autor_ = "";
        location_ = "";
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        if (!hasAutor()) {
          memoizedIsInitialized = 0;
          return false;
        }
        if (!hasLocation()) {
          memoizedIsInitialized = 0;
          return false;
        }
        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getAutorBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getLocationBytes());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getAutorBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getLocationBytes());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code messages.LogMessage.ID}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:messages.LogMessage.ID)
          de.fhwedel.ueb04.LogMessageProtos.LogMessage.IDOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return de.fhwedel.ueb04.LogMessageProtos.internal_static_messages_LogMessage_ID_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return de.fhwedel.ueb04.LogMessageProtos.internal_static_messages_LogMessage_ID_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.class, de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.Builder.class);
        }

        // Construct using de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          autor_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          location_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return de.fhwedel.ueb04.LogMessageProtos.internal_static_messages_LogMessage_ID_descriptor;
        }

        public de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID getDefaultInstanceForType() {
          return de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.getDefaultInstance();
        }

        public de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID build() {
          de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID buildPartial() {
          de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID result = new de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.autor_ = autor_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.location_ = location_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID) {
            return mergeFrom((de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID other) {
          if (other == de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.getDefaultInstance()) return this;
          if (other.hasAutor()) {
            bitField0_ |= 0x00000001;
            autor_ = other.autor_;
            onChanged();
          }
          if (other.hasLocation()) {
            bitField0_ |= 0x00000002;
            location_ = other.location_;
            onChanged();
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          if (!hasAutor()) {
            
            return false;
          }
          if (!hasLocation()) {
            
            return false;
          }
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        private java.lang.Object autor_ = "";
        /**
         * <code>required string autor = 1;</code>
         */
        public boolean hasAutor() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>required string autor = 1;</code>
         */
        public java.lang.String getAutor() {
          java.lang.Object ref = autor_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              autor_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string autor = 1;</code>
         */
        public com.google.protobuf.ByteString
            getAutorBytes() {
          java.lang.Object ref = autor_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            autor_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string autor = 1;</code>
         */
        public Builder setAutor(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          autor_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string autor = 1;</code>
         */
        public Builder clearAutor() {
          bitField0_ = (bitField0_ & ~0x00000001);
          autor_ = getDefaultInstance().getAutor();
          onChanged();
          return this;
        }
        /**
         * <code>required string autor = 1;</code>
         */
        public Builder setAutorBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          autor_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object location_ = "";
        /**
         * <code>required string location = 2;</code>
         */
        public boolean hasLocation() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>required string location = 2;</code>
         */
        public java.lang.String getLocation() {
          java.lang.Object ref = location_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            if (bs.isValidUtf8()) {
              location_ = s;
            }
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>required string location = 2;</code>
         */
        public com.google.protobuf.ByteString
            getLocationBytes() {
          java.lang.Object ref = location_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            location_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>required string location = 2;</code>
         */
        public Builder setLocation(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          location_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>required string location = 2;</code>
         */
        public Builder clearLocation() {
          bitField0_ = (bitField0_ & ~0x00000002);
          location_ = getDefaultInstance().getLocation();
          onChanged();
          return this;
        }
        /**
         * <code>required string location = 2;</code>
         */
        public Builder setLocationBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          location_ = value;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:messages.LogMessage.ID)
      }

      static {
        defaultInstance = new ID(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:messages.LogMessage.ID)
    }

    private int bitField0_;
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private java.lang.Object timestamp_;
    /**
     * <code>required string timestamp = 1;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string timestamp = 1;</code>
     */
    public java.lang.String getTimestamp() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          timestamp_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string timestamp = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTimestampBytes() {
      java.lang.Object ref = timestamp_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        timestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID id_;
    /**
     * <code>optional .messages.LogMessage.ID id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .messages.LogMessage.ID id = 2;</code>
     */
    public de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID getId() {
      return id_;
    }
    /**
     * <code>optional .messages.LogMessage.ID id = 2;</code>
     */
    public de.fhwedel.ueb04.LogMessageProtos.LogMessage.IDOrBuilder getIdOrBuilder() {
      return id_;
    }

    public static final int PRIORITY_FIELD_NUMBER = 3;
    private de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority priority_;
    /**
     * <code>required .messages.LogMessage.Priority priority = 3;</code>
     */
    public boolean hasPriority() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .messages.LogMessage.Priority priority = 3;</code>
     */
    public de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority getPriority() {
      return priority_;
    }

    public static final int CONTENT_FIELD_NUMBER = 4;
    private java.lang.Object content_;
    /**
     * <code>required string content = 4;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required string content = 4;</code>
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          content_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string content = 4;</code>
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      timestamp_ = "";
      id_ = de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.getDefaultInstance();
      priority_ = de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority.DEBUG;
      content_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPriority()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasContent()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasId()) {
        if (!getId().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, priority_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getContentBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTimestampBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, priority_.getNumber());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getContentBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static de.fhwedel.ueb04.LogMessageProtos.LogMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.fhwedel.ueb04.LogMessageProtos.LogMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.fhwedel.ueb04.LogMessageProtos.LogMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static de.fhwedel.ueb04.LogMessageProtos.LogMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static de.fhwedel.ueb04.LogMessageProtos.LogMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.fhwedel.ueb04.LogMessageProtos.LogMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static de.fhwedel.ueb04.LogMessageProtos.LogMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static de.fhwedel.ueb04.LogMessageProtos.LogMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static de.fhwedel.ueb04.LogMessageProtos.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static de.fhwedel.ueb04.LogMessageProtos.LogMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(de.fhwedel.ueb04.LogMessageProtos.LogMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code messages.LogMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:messages.LogMessage)
        de.fhwedel.ueb04.LogMessageProtos.LogMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return de.fhwedel.ueb04.LogMessageProtos.internal_static_messages_LogMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return de.fhwedel.ueb04.LogMessageProtos.internal_static_messages_LogMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                de.fhwedel.ueb04.LogMessageProtos.LogMessage.class, de.fhwedel.ueb04.LogMessageProtos.LogMessage.Builder.class);
      }

      // Construct using de.fhwedel.ueb04.LogMessageProtos.LogMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIdFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        timestamp_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (idBuilder_ == null) {
          id_ = de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.getDefaultInstance();
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        priority_ = de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority.DEBUG;
        bitField0_ = (bitField0_ & ~0x00000004);
        content_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return de.fhwedel.ueb04.LogMessageProtos.internal_static_messages_LogMessage_descriptor;
      }

      public de.fhwedel.ueb04.LogMessageProtos.LogMessage getDefaultInstanceForType() {
        return de.fhwedel.ueb04.LogMessageProtos.LogMessage.getDefaultInstance();
      }

      public de.fhwedel.ueb04.LogMessageProtos.LogMessage build() {
        de.fhwedel.ueb04.LogMessageProtos.LogMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public de.fhwedel.ueb04.LogMessageProtos.LogMessage buildPartial() {
        de.fhwedel.ueb04.LogMessageProtos.LogMessage result = new de.fhwedel.ueb04.LogMessageProtos.LogMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (idBuilder_ == null) {
          result.id_ = id_;
        } else {
          result.id_ = idBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.priority_ = priority_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.content_ = content_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof de.fhwedel.ueb04.LogMessageProtos.LogMessage) {
          return mergeFrom((de.fhwedel.ueb04.LogMessageProtos.LogMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(de.fhwedel.ueb04.LogMessageProtos.LogMessage other) {
        if (other == de.fhwedel.ueb04.LogMessageProtos.LogMessage.getDefaultInstance()) return this;
        if (other.hasTimestamp()) {
          bitField0_ |= 0x00000001;
          timestamp_ = other.timestamp_;
          onChanged();
        }
        if (other.hasId()) {
          mergeId(other.getId());
        }
        if (other.hasPriority()) {
          setPriority(other.getPriority());
        }
        if (other.hasContent()) {
          bitField0_ |= 0x00000008;
          content_ = other.content_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasPriority()) {
          
          return false;
        }
        if (!hasContent()) {
          
          return false;
        }
        if (hasId()) {
          if (!getId().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        de.fhwedel.ueb04.LogMessageProtos.LogMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (de.fhwedel.ueb04.LogMessageProtos.LogMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object timestamp_ = "";
      /**
       * <code>required string timestamp = 1;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string timestamp = 1;</code>
       */
      public java.lang.String getTimestamp() {
        java.lang.Object ref = timestamp_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            timestamp_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string timestamp = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTimestampBytes() {
        java.lang.Object ref = timestamp_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          timestamp_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string timestamp = 1;</code>
       */
      public Builder setTimestamp(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 1;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = getDefaultInstance().getTimestamp();
        onChanged();
        return this;
      }
      /**
       * <code>required string timestamp = 1;</code>
       */
      public Builder setTimestampBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        timestamp_ = value;
        onChanged();
        return this;
      }

      private de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID id_ = de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID, de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.Builder, de.fhwedel.ueb04.LogMessageProtos.LogMessage.IDOrBuilder> idBuilder_;
      /**
       * <code>optional .messages.LogMessage.ID id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .messages.LogMessage.ID id = 2;</code>
       */
      public de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID getId() {
        if (idBuilder_ == null) {
          return id_;
        } else {
          return idBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .messages.LogMessage.ID id = 2;</code>
       */
      public Builder setId(de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID value) {
        if (idBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          id_ = value;
          onChanged();
        } else {
          idBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .messages.LogMessage.ID id = 2;</code>
       */
      public Builder setId(
          de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.Builder builderForValue) {
        if (idBuilder_ == null) {
          id_ = builderForValue.build();
          onChanged();
        } else {
          idBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .messages.LogMessage.ID id = 2;</code>
       */
      public Builder mergeId(de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID value) {
        if (idBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              id_ != de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.getDefaultInstance()) {
            id_ =
              de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.newBuilder(id_).mergeFrom(value).buildPartial();
          } else {
            id_ = value;
          }
          onChanged();
        } else {
          idBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .messages.LogMessage.ID id = 2;</code>
       */
      public Builder clearId() {
        if (idBuilder_ == null) {
          id_ = de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.getDefaultInstance();
          onChanged();
        } else {
          idBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .messages.LogMessage.ID id = 2;</code>
       */
      public de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.Builder getIdBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getIdFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .messages.LogMessage.ID id = 2;</code>
       */
      public de.fhwedel.ueb04.LogMessageProtos.LogMessage.IDOrBuilder getIdOrBuilder() {
        if (idBuilder_ != null) {
          return idBuilder_.getMessageOrBuilder();
        } else {
          return id_;
        }
      }
      /**
       * <code>optional .messages.LogMessage.ID id = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID, de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.Builder, de.fhwedel.ueb04.LogMessageProtos.LogMessage.IDOrBuilder> 
          getIdFieldBuilder() {
        if (idBuilder_ == null) {
          idBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID, de.fhwedel.ueb04.LogMessageProtos.LogMessage.ID.Builder, de.fhwedel.ueb04.LogMessageProtos.LogMessage.IDOrBuilder>(
                  getId(),
                  getParentForChildren(),
                  isClean());
          id_ = null;
        }
        return idBuilder_;
      }

      private de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority priority_ = de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority.DEBUG;
      /**
       * <code>required .messages.LogMessage.Priority priority = 3;</code>
       */
      public boolean hasPriority() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .messages.LogMessage.Priority priority = 3;</code>
       */
      public de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority getPriority() {
        return priority_;
      }
      /**
       * <code>required .messages.LogMessage.Priority priority = 3;</code>
       */
      public Builder setPriority(de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        priority_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .messages.LogMessage.Priority priority = 3;</code>
       */
      public Builder clearPriority() {
        bitField0_ = (bitField0_ & ~0x00000004);
        priority_ = de.fhwedel.ueb04.LogMessageProtos.LogMessage.Priority.DEBUG;
        onChanged();
        return this;
      }

      private java.lang.Object content_ = "";
      /**
       * <code>required string content = 4;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required string content = 4;</code>
       */
      public java.lang.String getContent() {
        java.lang.Object ref = content_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            content_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string content = 4;</code>
       */
      public com.google.protobuf.ByteString
          getContentBytes() {
        java.lang.Object ref = content_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          content_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string content = 4;</code>
       */
      public Builder setContent(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 4;</code>
       */
      public Builder clearContent() {
        bitField0_ = (bitField0_ & ~0x00000008);
        content_ = getDefaultInstance().getContent();
        onChanged();
        return this;
      }
      /**
       * <code>required string content = 4;</code>
       */
      public Builder setContentBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        content_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:messages.LogMessage)
    }

    static {
      defaultInstance = new LogMessage(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:messages.LogMessage)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_LogMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_LogMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_messages_LogMessage_ID_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_messages_LogMessage_ID_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!de/fhwedel/ueb04/LogMessage.proto\022\010mes" +
      "sages\"\356\001\n\nLogMessage\022\021\n\ttimestamp\030\001 \002(\t\022" +
      "#\n\002id\030\002 \001(\0132\027.messages.LogMessage.ID\022/\n\010" +
      "priority\030\003 \002(\0162\035.messages.LogMessage.Pri" +
      "ority\022\017\n\007content\030\004 \002(\t\032%\n\002ID\022\r\n\005autor\030\001 " +
      "\002(\t\022\020\n\010location\030\002 \002(\t\"?\n\010Priority\022\t\n\005DEB" +
      "UG\020\000\022\010\n\004INFO\020\001\022\010\n\004WARN\020\002\022\t\n\005ERROR\020\003\022\t\n\005F" +
      "ATAL\020\004B$\n\020de.fhwedel.ueb04B\020LogMessagePr" +
      "otos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_messages_LogMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_messages_LogMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_LogMessage_descriptor,
        new java.lang.String[] { "Timestamp", "Id", "Priority", "Content", });
    internal_static_messages_LogMessage_ID_descriptor =
      internal_static_messages_LogMessage_descriptor.getNestedTypes().get(0);
    internal_static_messages_LogMessage_ID_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_messages_LogMessage_ID_descriptor,
        new java.lang.String[] { "Autor", "Location", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
